os: linux
language: python
python: pypy3.9-7.3.9
script: python -V

install: true

jobs:
  include:
    - dist: bionic
      arch: arm64
    - dist: focal
      arch: arm64
    - dist: jammy
      arch: arm64
