#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# waits:
# first wait to have at least one of a type, then wait for all to be in a state; if waiting for state with empty set, kubectl fails

name: Test skupper-router main

# on: [ push ]
on: [ workflow_dispatch ]

jobs:
  test-image:
    name: Publish skupper-router image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        skupperGitRef: [ 0.8.7 ]

    steps:

# Use currently built image
# also consider https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md but likely overkill
# $ docker save hello-web > hello-web.tar
# sudo microk8s.ctr -n k8s.io image import hello-web.tar
# sudo microk8s.ctr -n k8s.io images ls --name~=hello-web
# sudo docker build . -t localhost:32000/hello-web:v3

      - name: Get Go cache paths
        id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      # https://microk8s.io/docs/addon-metallb
      - name: Install microk8s
        run: |
          sudo snap install microk8s --classic --channel=1.21/stable
          sudo microk8s enable dns ingress registry:size=20Gi host-access:ip=10.0.1.1 metallb:10.64.140.43-10.64.140.49
          sudo microk8s status --wait-ready

      - name: Export microk8s config
        if: "${{ always() }}"
        run: |
          mkdir -p $HOME/.kube
          sudo microk8s config > $HOME/.kube/config

      - name: Checkout Skupper
        uses: actions/checkout@v2
        with:
          repository: 'skupperproject/skupper'
          ref: ${{ matrix.skupperGitRef }}
          path: 'skupper'

      - name: Restore Go cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.go-cache-paths.outputs.go-build }}
            ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Compile Skupper
        run: |
          make all
          sudo install skupper /usr/local/bin
        working-directory: skupper

      - name: Run Skupper integration tests
        run: |
          export QDROUTERD_IMAGE=quay.io/jdanek/skupper-router:latest
          export PUBLIC_1_INGRESS_HOST=10.0.1.1
          go test -count=1 -p=1 -timeout=60m -tags=integration -v ./test/integration/...
        working-directory: skupper

      # https://github.com/canonical/microk8s/issues/1660
      - name: Dump microk8s log (apiserver)
        if: "${{ always() }}"
        run: |
          sudo journalctl -u snap.microk8s.daemon-apiserver

      - name: Dump microk8s log (kubelet)
        if: "${{ always() }}"
        run: |
          sudo journalctl -u snap.microk8s.daemon-kubelet

      - name: Dump microk8s log (kubelite)
        if: "${{ always() }}"
        run: |
          sudo journalctl -u snap.microk8s.daemon-kubelite